### ISSUE TITLE
Unit testing examples

### ISSUE THREAD

**Issue by davecromberge** [CodeFX-org/demo-jpms-monitor#2]
Hi @nipafx,

A colleague and I have been working through your book about JPMS - we found it very helpful and informative.   However, we noticed that there is no material that covers unit testing.  Is it possible to add an example to this repository that demonstrates how this would work with modules, or is there a reference that you could recommend?  

From a cursory reading, others have added a separate unit testing module that requires the module under test.  Testing internals requires adding additional exports from the source to the test module.

I would be grateful for your help / any resources that you can provide.

Thank you,
David

**Comment by davecromberge** [comment]
I've managed to find a solution that has been proposed elsewhere, and in fact corresponds to a section of the book (section 4.1 Organizing your project in a directory structure).  The solution I have adopted creates a separate tests module for every src module, and uses exports and requires to gain access to the internal packages.

**Comment by nipafx** [comment]
Hi @davecromberge, sorry for taking a while to reply. Glad you found a solution.
